import {
  Film,
  Car,
  ShoppingBag,
  Utensils,
  Receipt,
  GraduationCap,
  HeartPulse,
  RefreshCw,
  CupSoda,
  Shapes,
} from "lucide-react";

// Helper to get category-specific styles and icons
export const categoryConfig = {
  food: {
    color: "bg-orange-50 text-orange-700 border border-orange-200",
    bgColor: "bg-orange-400",
    icon: <Utensils size={14} className="mr-1" />,
    largeIcon: <Utensils size={24} className="mr-1"/>,
    label: "Food",
  },
  drinks: {
    color: "bg-amber-50 text-amber-700 border border-amber-200",
    bgColor: "bg-amber-400",
    icon: <CupSoda size={14} className="mr-1" />,
    largeIcon: <CupSoda size={24} className="mr-1"/>,
    label: "Drinks",
  },
  shopping: {
    color: "bg-pink-50 text-pink-700 border border-pink-200",
    bgColor: "bg-pink-300",
    icon: <ShoppingBag size={14} className="mr-1" />,
    largeIcon: <ShoppingBag size={24} className="mr-1"/>,
    label: "Shopping",
  },
  bills: {
    color: "bg-red-50 text-red-700 border border-red-200",
    bgColor: "bg-red-400",
    icon: <Receipt size={14} className="mr-1" />,
    largeIcon: <Receipt size={24} className="mr-1"/>,
    label: "Bills",
  },
  education: {
    color: "bg-indigo-50 text-indigo-700 border border-indigo-200",
    bgColor: "bg-indigo-400",
    icon: <GraduationCap size={14} className="mr-1" />,
    largeIcon: <GraduationCap size={24} className="mr-1"/>,
    label: "Education",
  },
  health: {
    color: "bg-emerald-50 text-emerald-700 border border-emerald-200",
    bgColor: "bg-emerald-400",
    icon: <HeartPulse size={14} className="mr-1" />,
    largeIcon: <HeartPulse size={24} className="mr-1"/>,
    label: "Health",
  },
  entertainment: {
    color: "bg-purple-50 text-purple-700 border border-purple-200",
    bgColor: "bg-purple-400",
    icon: <Film size={14} className="mr-1" />,
    largeIcon: <Film size={24} className="mr-1"/>,
    label: "Entertainment",
  },
  transport: {
    color: "bg-blue-50 text-blue-700 border border-blue-200",
    bgColor: "bg-blue-400",
    icon: <Car size={14} className="mr-1" />,
    largeIcon: <Car size={24} className="mr-1"/>,
    label: "Transport",
  },
  subscriptions: {
    color: "bg-cyan-50 text-cyan-700 border border-cyan-200",
    bgColor: "bg-cyan-400",
    icon: <RefreshCw size={14} className="mr-1" />,
    largeIcon: <RefreshCw size={24} className="mr-1"/>,
    label: "Subscriptions",
  },
  other: {
    color: "bg-gray-50 text-gray-700 border border-gray-200",
    bgColor: "bg-gray-400",
    icon: <Shapes  size={14} className="mr-1"/>,
    largeIcon: <Shapes size={24} className="mr-1"/>,
    label: "Other",
  },
};
